### ISSUE TITLE
Header & Footer

### ISSUE THREAD

**Issue by moumot** [adrianreza96/ParkItMy#6]

**Comment by jaoeymaui** [comment]
Finalize Design for  of Webpage/App Header & Footer

**Comment by jaoeymaui** [comment]
Mot: Can you list down the dependencies you have on Shermaine as part of the comment? -Jao-

**Comment by moumot** [comment]
The design and the content for the header and footer

**Comment by Smaine33** [comment]
completed. please refer to the attachment on "dashboard".
